"""add commission fields to pagos

Revision ID: 952e4a49151b
Revises: ab91eb29b14b
Create Date: 2026-06-07 19:33:09.867196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952e4a49151b'
down_revision: Union[str, Sequence[str], None] = 'ab91eb29b14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_descuento_campana', 'descuentos', 'campanas_fidelizacion', ['campana_id'], ['id'], use_alter=True)
    op.add_column('pagos', sa.Column('trabajador_id', sa.UUID(), nullable=True))
    op.add_column('pagos', sa.Column('monto_bruto', sa.Float(), nullable=True))
    op.add_column('pagos', sa.Column('comision_porcentaje', sa.Float(), nullable=True))
    op.add_column('pagos', sa.Column('comision_monto', sa.Float(), nullable=True))
    op.add_column('pagos', sa.Column('monto_neto', sa.Float(), nullable=True))
    op.add_column('pagos', sa.Column('facturado', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'pagos', 'trabajadores', ['trabajador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pagos', type_='foreignkey')
    op.drop_column('pagos', 'facturado')
    op.drop_column('pagos', 'monto_neto')
    op.drop_column('pagos', 'comision_monto')
    op.drop_column('pagos', 'comision_porcentaje')
    op.drop_column('pagos', 'monto_bruto')
    op.drop_column('pagos', 'trabajador_id')
    op.drop_constraint('fk_descuento_campana', 'descuentos', type_='foreignkey')
    # ### end Alembic commands ###
